# Deploy documentation when push to main

name: Deploy docs

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install .[docs]
      - name: Deploy docs
        run: mkdocs gh-deploy --force
